apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyZXl2aTEyMyIsInBhc3N3b3JkIjoiZGNrcl9wYXRfYmRQZFVwNlhVN1U5c3BydGtmV1c4ejlnNzJFIiwiZW1haWwiOiIxNnR1bWUyMTFyYXZpcHJhc2F0aEBnbWFpbC5jb20iLCJhdXRoIjoiY21WNWRta3hNak02WkdOcmNsOXdZWFJmWW1SUVpGVndObGhWTjFVNWMzQnlkR3RtVjFjNGVqbG5OekpGIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
